import Head from 'next/head';

import dynamic from 'next/dynamic';

const WidgetBot = dynamic(() => import('@widgetbot/react-embed'), {
  ssr: false,
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="on"
        />\
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <div className="flex flex-col gap-8 py-6 px-6 max-w-[1440px] mx-auto">
          <div className="flex justify-between align-bottom">
            <div className="flex flex-col gap-1">
              <h2 className="text-3xl font-medium text-white">
                Ficou com alguma dúvida?
              </h2>
              <p className="text-2xl">Faça sua pergunta no canal do Discord:</p>
            </div>

            <div className="flex flex-col justify-end text-xl">
              <p>Ou, se preferir, mande para</p>
              <p className="text-orange-400 font-medium">
                contato@strangemike.com
              </p>
            </div>
          </div>

          <div
            className="flex justify-center align-center"
            suppressHydrationWarning
          >
            <WidgetBot
              server="798690805464301588"
              channel="798702383919530004"
              width="100%"
              height={650}
              style={{ borderBottom: '4px solid #EE723C' }}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
